version: '3'
services:
  url_shortener:
    build: ./url_shortener
    ports:
     - "5000:5000"
    environment:
      ENV: 'test'
    links:
     - redis_cache
  redis_cache:
    image: "redis:alpine"
